default_stages:
- commit

repos:
- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
    - id: black
      language_version: python3.8
      args:
        - -l 120
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.7.0
  hooks:
    - id: python-check-blanket-noqa

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.790
  hooks:
    - id: mypy
      entry: mypy .
      pass_filenames: false

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-docstring-first
    stages:
    - commit
    - push
  - id: check-merge-conflict
    stages:
    - push
  - id: flake8
    stages:
    - commit
    - push
    args:
    - --max-line-length=120
    - --ignore=E203,W503
  - id: trailing-whitespace
    stages:
    - commit
    - push
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: \.svg$
